function menuPrincipal(){
    document.write('<ul id="menuPrincipal">');
            document.write('<li><a href="index.html"><img src="images/home.png"></a></li>');
            document.write('<li>Los Juegos &raquo;');
                document.write('<ul>');
                    document.write('<li><a href="historia.html">Historia</a></li>');
					document.write('<li><a href="comite.html">Comité Organizador</a></li>');
					document.write('<li><a href="paises.html">Países Participantes</a></li>');
					document.write('<li><a href="logo.html">Logo</a></li>');
                    document.write('<li><a href="mascota.html">Mascota</a></li>');
                    document.write('<li><a href="medallas.html">Medallas y Diplomas</a></li>');
                document.write('</ul>');
            document.write('</li>');
            document.write('<li>Deportes &raquo;');
                document.write('<ul>');
                    document.write('<li><a href="#">Cronograma</a></li>');
                    document.write('<li><a href="pictograma.html">Pictogramas</a></li>');
                    document.write('<li><a href="autobus.html">Autobuses por Disciplina Deportiva</a></li>');
                document.write('</ul>');
            document.write('</li>');
            document.write('<li>Comunicación &raquo;');
                document.write('<ul>');
                    document.write('<li><a href="avisos.html">Aviso Promocional</a></li>');
                    document.write('<li><a href="material_publicitario.html">Material Publicitario</a></li>');
                    document.write('<li><a href="#">Material POP</a></li>');
                document.write('</ul>');
            document.write('</li>');
            document.write('<li>Sede &raquo;');
                document.write('<ul>');
                    document.write('<li><a href="#">Boletos</a></li>');
                    document.write('<li><a href="mapa.html">Mapa</a></li>');
                    document.write('<li><a href="senialetica.html">Señalética</a></li>');
                document.write('</ul>');
            document.write('</li>');
            document.write('<li>');
                document.write('<form action="" method="get">');
                    document.write('<select>');
                        document.write('<option value="">Seleccione...</option>');
                        document.write('<option value="">Aviso Promocional</option>');
                        document.write('<option value="">Autobuses por Disciplina Deportiva</option>');
                        document.write('<option value="">Boletos</option>');
                        document.write('<option value="">Cronograma</option>');
                        document.write('<option value="">Mapa</option>');
                        document.write('<option value="">Mascota</option>');
                        document.write('<option value="">Material POP</option>');
                        document.write('<option value="">Material Publicitario</option>');
                        document.write('<option value="">Medallas y Diplomas</option>');
                        document.write('<option value="">Logo</option>');
                        document.write('<option value="">Pictograma</option>');
                        document.write('<option value="">Señalética</option>');
                    document.write('</select>');
                    document.write('<button type="button">Buscar</button>');
                document.write('</form>');
            document.write('</li>');
        document.write('</ul>');
    }